# Generated by Django 3.0.11 on 2021-04-03 19:08

from django.db import migrations, models
import spacex_api.utils.mixins.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name_plural': 'status',
            },
            bases=(spacex_api.utils.mixins.models.NamesListingModelMixin, models.Model),
        ),
    ]
