# Generated by Django 3.0.11 on 2021-04-01 19:55

from django.db import migrations

def create_default_status(apps, schema_editor):  
    Status = apps.get_model("accounts", "Status")
    status = ['Issue', 'Bug', 'Task']
    for i in status:
        try:
            Status.objects.create(name=i)
        except (ValueError, TypeError):
            print("Imposible create status {}".format(i))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_status, migrations.RunPython.noop),
    ]
