# Generated by Django 3.0.11 on 2021-03-30 01:02

from django.db import migrations

def create_default_categories(apps, schema_editor):  
    Category = apps.get_model("accounts", "Category")
    categories = ['Mantenimiento', 'Investigación', 'Prueba']
    for i in categories:
        try:
            Category.objects.create(name=i)
        except (ValueError, TypeError):
            print("Imposible create category {}".format(i))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_default_status'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, migrations.RunPython.noop),
    ]
