# Generated by Django 3.0.11 on 2021-03-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='trello_list',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
