# Generated by Django 3.0.11 on 2021-04-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='trello_username',
        ),
    ]
