# Generated by Django 3.0.11 on 2021-03-30 01:19

# Django
from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_superuser(apps, schema_editor):  
    User = apps.get_model("users", "User")
    User.objects.create(username="admin",
                        first_name="John",
                        last_name="Doe",
                        email="admin@admin.com",
                        password=make_password("admin1234"),
                        is_staff=True,
                        is_superuser=True,)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser, migrations.RunPython.noop),
    ]
