# Generated by Django 3.0.11 on 2021-03-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_default_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trello_key',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trello_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
