# Generated by Django 3.0.11 on 2021-04-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210330_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trello_board_id',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
