# Generated by Django 3.0.11 on 2021-03-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210330_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trello_username',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
