site_name: Space-x
site_dir: /docs/_build

nav:
    - Home: index.md
    - Database: 
        - Default values: database/default_values.md
    - API Guide:
        - Status codes: status_codes.md
    - Endpoints:
        - Sign up: endpoints/users.md
        - Login: endpoints/tokens_and_login.md
        - Trello: endpoints/trello.md

theme: readthedocs